CREATE TABLE IF NOT EXISTS ativo_financeiro_rede (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo_financeiro_id BIGINT NOT NULL,
    rede_id BIGINT NOT NULL,
    identificador VARCHAR(150) NOT NULL,
    quantidade_casas_decimais INTEGER DEFAULT 6 NOT NULL,
    CONSTRAINT fk_ativo_financeiro_rede_ativo FOREIGN KEY (ativo_financeiro_id) REFERENCES ativo_financeiro (id),
    CONSTRAINT fk_ativo_financeiro_rede_rede FOREIGN KEY (rede_id) REFERENCES rede (id),
    CONSTRAINT uk_ativo_financeiro_rede_ativo_rede UNIQUE (ativo_financeiro_id, rede_id)
);
