# Database Configuration
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./db/cryptodb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
quarkus.hibernate-orm.database.generation=update

# JWT Configuration
mp.jwt.verify.publickey.location=classpath:public_key.pem
smallrye.jwt.sign.key.location=classpath:private_key.pem
smallrye.jwt.new-token.lifetime=31536000

# HTTP Configuration
quarkus.http.host=0.0.0.0
quarkus.http.port=9001

# REST Clients
quarkus.rest-client.binance-api.url=https://api.binance.com

# Logging
quarkus.log.level=INFO
quarkus.log.category."org.acme".level=DEBUG
quarkus.log.category."io.smallrye.jwt".level=TRACE
quarkus.log.category."io.quarkus.security".level=TRACE
smallrye.jwt.new-token.issuer=https://openclaw-dicop.duckdns.org/crypto-manager/v1/
mp.jwt.verify.issuer=https://openclaw-dicop.duckdns.org/crypto-manager/v1/
